export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SEARCH_DOCUMENT_SUCCESS = 'SEARCH_DOCUMENT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';
export const GET_USER_DOCUMENT_SUCCESS = 'GET_USER_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const SEARCH_DOCUMENTBYID_SUCCESS = 'SEARCH_DOCUMENTBYID_SUCCESS';

